CREATE TABLE EQUIPO(
		ID_EQUIPO VARCHAR2 NOT NULL,
            NOMBRE_EQUIPO VARCHAR2,
            CONSTRAINT PK_EQUIPO PRIMARY KEY (ID_EQUIPO)
);

		INSERT INTO EQUIPO VALUES ('1','Equipo 1');
		INSERT INTO EQUIPO VALUES ('2','Equipo 2');
		INSERT INTO EQUIPO VALUES ('3','Equipo 3');
		INSERT INTO EQUIPO VALUES ('4','Equipo 4');
		INSERT INTO EQUIPO VALUES ('5','Equipo 5');
		INSERT INTO EQUIPO VALUES ('6','Equipo 6');
		INSERT INTO EQUIPO VALUES ('7','Equipo 7');
		INSERT INTO EQUIPO VALUES ('8','Equipo 8');
		INSERT INTO EQUIPO VALUES ('9','Equipo 9');
		INSERT INTO EQUIPO VALUES ('10','Equipo 10');
		INSERT INTO EQUIPO VALUES ('11','Equipo 11');
		INSERT INTO EQUIPO VALUES ('12','Equipo 12');
		INSERT INTO EQUIPO VALUES ('13','Equipo 13');
		INSERT INTO EQUIPO VALUES ('14','Equipo 14');
		INSERT INTO EQUIPO VALUES ('15','Equipo 15');
		INSERT INTO EQUIPO VALUES ('16','Equipo 16');
		INSERT INTO EQUIPO VALUES ('17','Equipo 17');
		INSERT INTO EQUIPO VALUES ('18','Equipo 18');
		INSERT INTO EQUIPO VALUES ('19','Equipo 19');
		INSERT INTO EQUIPO VALUES ('20','Equipo 20');
		INSERT INTO EQUIPO VALUES ('21','Equipo 21');
		INSERT INTO EQUIPO VALUES ('22','Equipo 22');
		INSERT INTO EQUIPO VALUES ('23','Equipo 23');
		INSERT INTO EQUIPO VALUES ('24','Equipo 24');
		INSERT INTO EQUIPO VALUES ('25','Equipo 25');
		INSERT INTO EQUIPO VALUES ('26','Equipo 26');
		INSERT INTO EQUIPO VALUES ('27','Equipo 27');
		INSERT INTO EQUIPO VALUES ('28','Equipo 28');
		INSERT INTO EQUIPO VALUES ('29','Equipo 29');
		INSERT INTO EQUIPO VALUES ('30','Equipo 30');
		INSERT INTO EQUIPO VALUES ('31','Equipo 31');
		INSERT INTO EQUIPO VALUES ('32','Equipo 32');
