CREATE TABLE ESTADIO(
		ID_LUGAR VARCHAR2 NOT NULL,
            NOMBRE_ESTADIO VARCHAR2,
            CONSTRAINT PK_ESTADIO PRIMARY KEY (ID_LUGAR)
);

		INSERT INTO ESTADIO VALUES ('1','Estadio 1');
		INSERT INTO ESTADIO VALUES ('2','Estadio 2');
		INSERT INTO ESTADIO VALUES ('3','Estadio 3');
		INSERT INTO ESTADIO VALUES ('4','Estadio 4');
		INSERT INTO ESTADIO VALUES ('5','Estadio 5');
