CREATE TABLE GRUPO(
		ID_GRUPO VARCHAR2 NOT NULL,
        CONSTRAINT PK_GRUPO PRIMARY KEY (ID_GRUPO)
);
		INSERT INTO GRUPO VALUES ('A','Grupo 1');
		INSERT INTO GRUPO VALUES ('B','Grupo 2');
		INSERT INTO GRUPO VALUES ('C','Grupo 3');
		INSERT INTO GRUPO VALUES ('D','Grupo 4');
		INSERT INTO GRUPO VALUES ('E','Grupo 5');
		INSERT INTO GRUPO VALUES ('F','Grupo 6');
		INSERT INTO GRUPO VALUES ('G','Grupo 7');
		INSERT INTO GRUPO VALUES ('H','Grupo 8');
