CREATE TABLE PROGRAMACION(
			NUMPARTIDO VARCHAR2 NOT NULL,
            FECHA DATE,
            ID_LUGAR VARCHAR2,
            ID_FASE VARCHAR2,
            ID_GRUPO VARCHAR2,
            ID_EQUIPO VARCHAR2,
            EQU_ID_GRUPO VARCHAR2,
            EQU_ID_EQUIPO VARCHAR2,
            CONSTRAINT PK_PROGRAMACION PRIMARY KEY (NUMPARTIDO)
);

INSERT INTO PROGRAMACION VALUES ('1',TO_DATE('SYSDATE','DD-MM-YYYY'),'1','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('2',TO_DATE('SYSDATE','DD-MM-YYYY'),'2','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('3',TO_DATE('SYSDATE','DD-MM-YYYY'),'3','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('4',TO_DATE('SYSDATE','DD-MM-YYYY'),'4','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('5',TO_DATE('SYSDATE','DD-MM-YYYY'),'5','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('6',TO_DATE('SYSDATE','DD-MM-YYYY'),'1','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('7',TO_DATE('SYSDATE','DD-MM-YYYY'),'2','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('8',TO_DATE('SYSDATE','DD-MM-YYYY'),'3','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('9',TO_DATE('SYSDATE','DD-MM-YYYY'),'4','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('10',TO_DATE('SYSDATE','DD-MM-YYYY'),'5','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('11',TO_DATE('SYSDATE','DD-MM-YYYY'),'1','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('12',TO_DATE('SYSDATE','DD-MM-YYYY'),'2','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('13',TO_DATE('SYSDATE','DD-MM-YYYY'),'3','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('14',TO_DATE('SYSDATE','DD-MM-YYYY'),'4','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('15',TO_DATE('SYSDATE','DD-MM-YYYY'),'5','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('16',TO_DATE('SYSDATE','DD-MM-YYYY'),'1','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('17',TO_DATE('SYSDATE','DD-MM-YYYY'),'2','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('18',TO_DATE('SYSDATE','DD-MM-YYYY'),'3','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('19',TO_DATE('SYSDATE','DD-MM-YYYY'),'4','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('20',TO_DATE('SYSDATE','DD-MM-YYYY'),'5','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('21',TO_DATE('SYSDATE','DD-MM-YYYY'),'1','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('22',TO_DATE('SYSDATE','DD-MM-YYYY'),'2','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('23',TO_DATE('SYSDATE','DD-MM-YYYY'),'3','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('24',TO_DATE('SYSDATE','DD-MM-YYYY'),'4','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('25',TO_DATE('SYSDATE','DD-MM-YYYY'),'5','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('26',TO_DATE('SYSDATE','DD-MM-YYYY'),'1','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('27',TO_DATE('SYSDATE','DD-MM-YYYY'),'2','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('28',TO_DATE('SYSDATE','DD-MM-YYYY'),'3','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('29',TO_DATE('SYSDATE','DD-MM-YYYY'),'4','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('30',TO_DATE('SYSDATE','DD-MM-YYYY'),'5','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('31',TO_DATE('SYSDATE','DD-MM-YYYY'),'1','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('32',TO_DATE('SYSDATE','DD-MM-YYYY'),'2','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('33',TO_DATE('SYSDATE','DD-MM-YYYY'),'3','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('34',TO_DATE('SYSDATE','DD-MM-YYYY'),'4','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('35',TO_DATE('SYSDATE','DD-MM-YYYY'),'5','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('36',TO_DATE('SYSDATE','DD-MM-YYYY'),'1','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('37',TO_DATE('SYSDATE','DD-MM-YYYY'),'2','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('38',TO_DATE('SYSDATE','DD-MM-YYYY'),'3','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('39',TO_DATE('SYSDATE','DD-MM-YYYY'),'4','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('40',TO_DATE('SYSDATE','DD-MM-YYYY'),'5','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('41',TO_DATE('SYSDATE','DD-MM-YYYY'),'1','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('42',TO_DATE('SYSDATE','DD-MM-YYYY'),'2','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('43',TO_DATE('SYSDATE','DD-MM-YYYY'),'3','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('44',TO_DATE('SYSDATE','DD-MM-YYYY'),'4','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('45',TO_DATE('SYSDATE','DD-MM-YYYY'),'5','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('46',TO_DATE('SYSDATE','DD-MM-YYYY'),'1','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('47',TO_DATE('SYSDATE','DD-MM-YYYY'),'2','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('48',TO_DATE('SYSDATE','DD-MM-YYYY'),'3','Grupos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('49',TO_DATE('SYSDATE','DD-MM-YYYY'),'4','Octavos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('50',TO_DATE('SYSDATE','DD-MM-YYYY'),'5','Octavos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('51',TO_DATE('SYSDATE','DD-MM-YYYY'),'1','Octavos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('52',TO_DATE('SYSDATE','DD-MM-YYYY'),'2','Octavos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('53',TO_DATE('SYSDATE','DD-MM-YYYY'),'3','Octavos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('54',TO_DATE('SYSDATE','DD-MM-YYYY'),'4','Octavos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('55',TO_DATE('SYSDATE','DD-MM-YYYY'),'5','Octavos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('56',TO_DATE('SYSDATE','DD-MM-YYYY'),'1','Octavos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('57',TO_DATE('SYSDATE','DD-MM-YYYY'),'2','Cuartos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('58',TO_DATE('SYSDATE','DD-MM-YYYY'),'3','Cuartos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('59',TO_DATE('SYSDATE','DD-MM-YYYY'),'4','Cuartos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('60',TO_DATE('SYSDATE','DD-MM-YYYY'),'5','Cuartos',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('61',TO_DATE('SYSDATE','DD-MM-YYYY'),'1','Semifinal',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('62',TO_DATE('SYSDATE','DD-MM-YYYY'),'2','Semifinal',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('63',TO_DATE('SYSDATE','DD-MM-YYYY'),'3','Tercer Puesto',NULL,NULL,NULL,NULL);
INSERT INTO PROGRAMACION VALUES ('64',TO_DATE('SYSDATE','DD-MM-YYYY'),'4','Final',NULL,NULL,NULL,NULL);
